name: seastatecci_whales
channels:
  - conda-forge
dependencies:
    - python=3.10
    - pip
    #- os
    - numpy
    - matplotlib
    #- sys
    - scipy
    #- traceback
    #- re
    #- math
    #- pickle
    #- datetime
    - netcdf4
    - h5py
    #- pip:
    #  - install tables
