name: seastatecci_whales
channels:
dependencies:
    - python>=2
    - pip
    #- os
    - numpy
    - matplotlib
    #- sys
    - scipy
    #- traceback
    #- re
    #- math
    #- pickle
    #- datetime
    - netcdf4
    - h5py
    - pip:
      - install tables
